CREATE TABLE veterinarians(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(255),
    created_at DATETIME NOT NULL,
	updated_at DATETIME DEFAULT NULL,
	deleted_at DATETIME DEFAULT NULL,
	is_active BOOLEAN DEFAULT FALSE
);

CREATE TABLE tutors(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(255),
    created_at DATETIME NOT NULL,
	updated_at DATETIME DEFAULT NULL,
	deleted_at DATETIME DEFAULT NULL,
	is_active BOOLEAN DEFAULT FALSE
);