spring:
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/medical_consultation?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
